### ISSUE TITLE
核心不开源？

### ISSUE THREAD

**Issue by maskedeken** [happycbbboy/v2cbb-android#1]

**Comment by happycbbboy** [comment]
非常感谢您的来信！

但是我没有任何核心可以开源

maskedeken ***@***.***> 于2024年3月12日周二 23:19写道：

**Comment by maskedeken** [comment]
我看到sdk只有一个aar

**Comment by happycbbboy** [comment]
我非常开心收到您的回复！
但是请不要一开始就指责我，我没有必要接受您的任何指责
我的aar文件不会开源，我生活比较困难，我希望靠它去挣点钱补贴家用
如果您有需要可以给我发送email邮件，我可以通过by me a coffee的商品出售给您
如果您希望资助我，同样也可以在by me a coffee上捐助我

**Comment by maskedeken** [comment]
> 我非常开心收到您的回复！ 但是请不要一开始就指责我，我没有必要接受您的任何指责 我的aar文件不会开源，我生活比较困难，我希望靠它去挣点钱补贴家用 如果您有需要可以给我发送email邮件，我可以通过by me a coffee的商品出售给您 如果您希望资助我，同样也可以在by me a coffee上捐助我

没有指责的意思，只是我习惯使用软件之前都对代码进行审计
